// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fermonuajvigzziqglnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlcm1vbnVhanZpZ3p6aXFnbG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTE1MjAsImV4cCI6MjA3MDAyNzUyMH0.88XmJT5mOKnSF3-nsqYwi8mkzt9ourECRGJxegzGA6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});